services:
  orphanage:
    container_name: orphanage
    build:
      context: https://github.com/thenunner/orphanage.git
      dockerfile: Dockerfile
    working_dir: /appdata/orphanage
    command: >
      uvicorn app:app
      --host 0.0.0.0
      --port 3750
    ports:
      - "3750:3750"
    volumes:
      # App code + gui + config (current directory)
      - ./:/appdata/orphanage:rw

      # Your data directory - EDIT THIS PATH
      # Examples:
      # Unraid: /mnt/user/data:/data:rw
      # Synology: /volume1/downloads:/data:rw
      # Linux: /home/user/downloads:/data:rw
      # Windows: C:/Downloads:/data:rw
      - /your/data/path:/data:rw

    # If using Unraid, add so WebUI is available in GUI
    #
    #labels:
    #  net.unraid.docker.webui: "http://[IP]:3750"
    #  net.unraid.docker.icon: "https://raw.githubusercontent.com/thenunner/orphanage/main/orphanage.png"

    environment:
      - TZ=America/Chicago
      - PYTHONUNBUFFERED=1

    networks: 
      - yourqbitcontainernetwork

    # Run as user - adjust for your system
    # Unraid: "99:100"
    # Most Linux: "1000:1000" 
    user: "99:100"

    restart: unless-stopped

networks:
  "yourqbitcontainernetwork": 
    external: true
